
services:
    
    nginx:
        container_name: nginx
        image: nginx:1.27.0
        network_mode: host
        volumes:
            - ./conf:/etc/nginx/conf.d
            - ./apps:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt/:/etc/letsencrypt
